version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py test api &&
             python3 manage.py runserver 0.0.0.0:8080"
    env_file:
      - ./.env.dev
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    env_file:
      - ./.env.dev
    #    volumes:
    #      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend
      dockerfile: .
    environment:
      - REACT_APP_SERVER_HOST=localhost
      - REACT_APP_SERVER_PORT=8080
    ports:
      - "3002:80"
    restart: on-failure

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: on-failure

  celery:
    restart: always
    build:
      context: .
    command: "celery -A marketing_rest_api.celery worker -B --pidfile= --loglevel=DEBUG"
    volumes:
      - ./:/app
    env_file:
      - ./.env.dev
    depends_on:
      - redis
      - app

volumes:
  pgdata: