# Generated by Django 4.0 on 2021-12-24 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=200)),
                ('objective', models.CharField(choices=[('APP_INSTALLS', 'APP_INSTALLS'), ('BRAND_AWARENESS', 'BRAND_AWARENESS'), ('CONVERSIONS', 'CONVERSIONS'), ('EVENT_RESPONSES', 'EVENT_RESPONSES'), ('LEAD_GENERATION', 'LEAD_GENERATION'), ('LINK_CLICKS', 'LINK_CLICKS'), ('LOCAL_AWARENESS', 'LOCAL_AWARENESS'), ('MESSAGES', 'MESSAGES'), ('OFFER_CLAIMS', 'OFFER_CLAIMS'), ('PAGE_LIKES', 'PAGE_LIKES'), ('POST_ENGAGEMENT', 'POST_ENGAGEMENT'), ('PRODUCT_CATALOG_SALES', 'PRODUCT_CATALOG_SALES'), ('REACH', 'REACH'), ('STORE_VISITS', 'STORE_VISITS'), ('VIDEO_VIEWS', 'VIDEO_VIEWS')], default='REACH', max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INHERITED_FROM_SOURCE', 'INHERITED_FROM_SOURCE'), ('PAUSED', 'PAUSED')], default='PAUSED', max_length=32)),
                ('condition', models.CharField(choices=[('IDLE', 'Idle'), ('WAITING', 'Waiting'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='IDLE', max_length=32)),
                ('error_payload', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'db_campaign',
            },
        ),
        migrations.CreateModel(
            name='AdSetModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_set_id', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('daily_budget', models.CharField(default='2000', max_length=64)),
                ('bid', models.CharField(default='5', max_length=64)),
                ('billing_event', models.CharField(choices=[('APP_INSTALLS', 'APP_INSTALLS'), ('CLICKS', 'CLICKS'), ('IMPRESSIONS', 'IMPRESSIONS'), ('LINK_CLICKS', 'LINK_CLICKS'), ('LISTING_INTERACTION', 'LISTING_INTERACTION'), ('NONE', 'NONE'), ('OFFER_CLAIMS', 'OFFER_CLAIMS'), ('PAGE_LIKES', 'PAGE_LIKES'), ('POST_ENGAGEMENT', 'POST_ENGAGEMENT'), ('PURCHASE', 'PURCHASE'), ('THRUPLAY', 'THRUPLAY')], max_length=64)),
                ('optimization_goal', models.CharField(choices=[('AD_RECALL_LIFT', 'AD_RECALL_LIFT'), ('APP_INSTALLS', 'APP_INSTALLS'), ('APP_INSTALLS_AND_OFFSITE_CONVERSIONS', 'APP_INSTALLS_AND_OFFSITE_CONVERSIONS'), ('CONVERSATIONS', 'CONVERSATIONS'), ('DERIVED_EVENTS', 'DERIVED_EVENTS'), ('ENGAGED_USERS', 'ENGAGED_USERS'), ('EVENT_RESPONSES', 'EVENT_RESPONSES'), ('IMPRESSIONS', 'IMPRESSIONS'), ('LANDING_PAGE_VIEWS', 'LANDING_PAGE_VIEWS'), ('LEAD_GENERATION', 'LEAD_GENERATION'), ('LINK_CLICKS', 'LINK_CLICKS'), ('NONE', 'NONE'), ('OFFSITE_CONVERSIONS', 'OFFSITE_CONVERSIONS'), ('PAGE_LIKES', 'PAGE_LIKES'), ('POST_ENGAGEMENT', 'POST_ENGAGEMENT'), ('QUALITY_CALL', 'QUALITY_CALL'), ('QUALITY_LEAD', 'QUALITY_LEAD'), ('REACH', 'REACH'), ('THRUPLAY', 'THRUPLAY'), ('VALUE', 'VALUE'), ('VISIT_INSTAGRAM_PROFILE', 'VISIT_INSTAGRAM_PROFILE')], max_length=64)),
                ('targeting', models.TextField(default="{'geo_locations': {'countries': ['AE', 'SA', 'KW']}, 'age_min': 20, 'age_max': 35}")),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INHERITED_FROM_SOURCE', 'INHERITED_FROM_SOURCE'), ('PAUSED', 'PAUSED')], default='PAUSED', max_length=32)),
                ('condition', models.CharField(choices=[('IDLE', 'Idle'), ('WAITING', 'Waiting'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='IDLE', max_length=32)),
                ('error_payload', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adsets', to='api.campaignmodel')),
            ],
            options={
                'db_table': 'db_ad_set',
            },
        ),
        migrations.CreateModel(
            name='AdModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ad_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('creative_name', models.CharField(max_length=256)),
                ('page_id', models.CharField(default=None, max_length=64)),
                ('creative_message', models.TextField()),
                ('creative_link', models.TextField()),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INHERITED_FROM_SOURCE', 'INHERITED_FROM_SOURCE'), ('PAUSED', 'PAUSED')], default='PAUSED', max_length=32)),
                ('condition', models.CharField(choices=[('IDLE', 'Idle'), ('WAITING', 'Waiting'), ('PUBLISHED', 'Published'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled')], default='IDLE', max_length=32)),
                ('error_payload', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('ad_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.adsetmodel')),
            ],
            options={
                'db_table': 'db_ad',
            },
        ),
    ]
