# Generated by Django 4.0 on 2021-12-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsetmodel',
            name='creative_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
