# Generated by Django 4.0 on 2021-12-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adsetmodel_creative_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsetmodel',
            name='creative_id',
        ),
        migrations.AddField(
            model_name='admodel',
            name='creative_id',
            field=models.CharField(default='', max_length=64),
        ),
    ]
